  version: '3'
  services:
    yToolsBox-db:
      container_name: 'yToolsBox-db'
      image: postgres
      restart: always
      ports:
        - 5432:5432
      volumes:
        - db-data:/var/lib/postgresql/data
      networks:
        - network
      environment:
        POSTGRES_PASSWORD: test123456

    yToolsBox-api:
      container_name: 'yToolsBox-api'
      build:
        context: ./ytoolsbox-gin
        dockerfile: Dockerfile
      image: yanqiaoyu/ytoolsbox-api:v0.2
      depends_on:
        - yToolsBox-db
      networks:
        - network
      volumes:
        - /home/yToolsBox/api/Script:/root/Script
      # should be same as above path
      environment:
        HOST_SCRIPT_PATH: /home/yToolsBox/api/Script
      ports:
        - 8081:8081
      command: ["sh", "wait-for", "yToolsBox-db:5432", "--", "./main", "-m", "production"]

    yToolsBox-dashboard:
      container_name: 'yToolsBox-dashboard'
      build:
        context: ./ytoolsbox-vue
        dockerfile: Dockerfile
      image: yanqiaoyu/ytoolsbox-dashboard:v0.2
      networks:
        - network
      ports:
        - 80:80
      depends_on:
        - yToolsBox-db
        - yToolsBox-api

  volumes:
    db-data:
  networks:
    network:
      driver: bridge
