server:
  port: 8081
datasource:
  host: 103.44.241.227
  # host: yToolsBox-api
  port: 5432
  database: postgres
  username: postgres
  password: test123456
  charset: utf8
tool:
  scriptBasePath: Script
