server:
  port: 8081
datasource:
  testhost: 103.44.241.227
  productionhost: yToolsBox-db
  port: 5432
  database: postgres
  username: postgres
  password: test123456
  charset: utf8
tool:
  scriptBasePath: Script
